function createfigure(X1, Y1, Y2, Y3, low, high, labelx)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 20-Jan-2019 08:03:11

% Create figure
figure1 = figure;
% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,Y1,'LineWidth',2,'Parent',axes1);
plot2 = plot(X1,Y2,'LineWidth',2,'Parent',axes1);
plot3 = plot(X1,Y3,'LineWidth',2,'Parent',axes1);
set(plot1,'DisplayName','Proposed','Marker','square','Color',[1 0 0]);
set(plot2,'DisplayName','RDWT-SVD','Marker','+','Color',[0 0 1]);
set(plot3,'DisplayName','IWT-SVD','Marker','*','Color',[0 1 0]);

% Create ylabel
ylabel('NC','FontWeight','bold');

% Create xlabel
xlabel(labelx,'FontWeight','bold');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[low high]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',12,'FontWeight','bold','XGrid','on','YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.130413388422742 0.928428427488716 0.773129918663873 0.0690690673686361],...
    'Orientation','horizontal');

